services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DATABASE_PROVIDER: postgres
      DATABASE_CONNECTION_STRING: host=postgres user=postgres password=postgres dbname=orders_demo port=5432 sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
